export const ALL_AUTHORS_REQUEST = 'ALL_AUTHORS_REQUEST'
export const ALL_AUTHORS_SUCCESS = 'ALL_AUTHORS_SUCCESS'
export const ALL_AUTHORS_FAIL = 'ALL_AUTHORS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const AUTHOR_DETAILS_REQUEST = 'AUTHOR_DETAILS_REQUEST'
export const AUTHOR_DETAILS_SUCCESS = 'AUTHOR_DETAILS_SUCCESS'
export const AUTHOR_DETAILS_FAIL = 'AUTHOR_DETAILS_FAIL'
